feat: gawr-664 add oslo municipality
Informatievlaanderen/public-api pull request #314
Opened 2021-11-30 11:03 UTC by lvermeulen

2021-11-30 11:57 UTC, lvermeulen commented
tweede commit omdat ik CODEOWNERS heb aangepast

2021-11-30 12:09 UTC, ArneD requested changes

2021-11-30 12:09 UTC, ArneD commented on src/Public.Api/Municipality/Oslo/MunicipalityOsloController-Get.cs
> +        /// Vraag een gemeente op.
"Vraag een gemeente op in OSLO formaat"?

2021-11-30 12:09 UTC, ArneD commented on src/Public.Api/Municipality/Oslo/MunicipalityOsloController-List.cs
> +        /// Vraag een lijst met gemeenten op.
"Vraag een lijst met gemeenten op in OSLO formaat."

2021-12-01 12:26 UTC, ArneD commented
superseded by #315

2021-12-01 12:26 UTC, closed without merging