feat: add status controller consumer
Informatievlaanderen/public-api pull request #741
Opened 2023-06-09 13:46 UTC by emalfroy

2023-06-09 14:22 UTC, pgallik approved these changes

2023-06-12 06:34 UTC, ArneD requested changes
You don't need a consumer url since projector url is already present.

2023-06-12 06:37 UTC, jvandaal approved these changes

2023-06-12 09:33 UTC, ArneD requested changes

2023-06-13 09:29 UTC, merged

2023-06-13 09:34 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 5.79.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/public-api/releases/tag/v5.79.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: